export function getWords() {
    return [
        'DJ',
        'œil',
        'ile',
        'trou',
        'kiwi',
        'lent',
        'côte',
        'paris',
        'table',
        'mugir',
        'métro',
        'vigne',
        'pizza',
        'crepe',
        'radis',
        'bague',
        'sable',
        'vague',
        'huile',
        'fanta',
        'orage',
        'chiot',
        'panda',
        'phare',
        'loupe',
        'prison',
        'jambes',
        'chaton',
        'parent',
        'citron',
        'sakura',
        'matelas',
        'oxygene',
        'citroen',
        'bretzel',
        'armoire',
        'trousse',
        'collant',
        'chambre',
        'ceinture',
        'marmotte',
        'batterie',
        'retraite',
        'internet',
        'danseuse',
        'cheville',
        'trombone',
        'champagne',
        'cuisinier',
        'tarentule',
        'detective',
        'caoutchouc',
        'sage-femme',
        'micro-ondes',
        'helicoptere',
        'pom-pom girl',
        'lampe torche',
        'tapis de bain',
        'table de nuit',
        'planche de surf',
        'marchand de glace',
        'lunettes de soleil',
    ];
}
