export function getWords() {
    return [
        'œil',
        'ile',
        'trou',
        'kiwi',
        'lent',
        'vigne',
        'pizza',
        'crepe',
        'radis',
        'sable',
        'bague',
        'vague',
        'huile',
        'fanta',
        'orage',
        'chiot',
        'panda',
        'phare',
        'jambes',
        'chaton',
        'parent',
        'collant',
        'chambre',
        'oxygene',
        'citroen',
        'batterie',
        'retraite',
        'internet',
        'danseuse',
        'cheville',
        'trombone',
        'champagne',
        'cuisinier',
        'tarentule',
        'caoutchouc',
        'sage-femme',
        'micro-ondes',
        'helicoptere',
        'lampe torche',
        'table de nuit',
        'planche de surf',
        'lunettes de soleil',
    ];
}
