export function getWords() {
    return [
        'DJ',
        'œil',
        'ile',
        'oie',
        'mur',
        'trou',
        'kiwi',
        'lent',
        'côte',
        'nemo',
        'pain',
        'slam',
        'clou',
        'faim',
        'paris',
        'table',
        'mugir',
        'métro',
        'vigne',
        'pizza',
        'crepe',
        'radis',
        'bague',
        'sable',
        'vague',
        'huile',
        'fanta',
        'orage',
        'chiot',
        'panda',
        'phare',
        'loupe',
        'poire',
        'nuage',
        'danse',
        'piano',
        'fumée',
        'poêle',
        'prison',
        'jambes',
        'chaton',
        'parent',
        'citron',
        'sakura',
        'réseau',
        'verrue',
        'matelas',
        'oxygene',
        'citroen',
        'bretzel',
        'armoire',
        'trousse',
        'collant',
        'chambre',
        'piscine',
        'piscine',
        'chapeau',
        'silence',
        'ceinture',
        'marmotte',
        'batterie',
        'retraite',
        'internet',
        'danseuse',
        'cheville',
        'trombone',
        'patinage',
        'tracteur',
        'champagne',
        'cuisinier',
        'tarentule',
        'detective',
        'shampoing',
        'Capitaine',
        'caoutchouc',
        'sage-femme',
        'micro-ondes',
        'helicoptere',
        'pom-pom girl',
        'lampe torche',
        'masque à gaz',
        'vélociraptor',
        'teletuzbbies',
        'tapis de bain',
        'table de nuit',
        'lance-flammes',
        'planche de surf',
        'alarme incendie',
        'marchand de glace',
        'lunettes de soleil',
        'bottle flip challenge',
        'Dragon blanc aux yeux bleus',
    ];
}
